(TeX-add-style-hook
 "chap1"
 (lambda ()
   (TeX-run-style-hooks
    "chapters/intro/intro-motivation"
    "chapters/intro/intro-replearning"
    "chapters/intro/intro-contribution"
    "chapters/intro/intro-roadmap")
   (LaTeX-add-labels
    "chap:intro"
    "eq:argmin")
   (LaTeX-add-index-entries
    "gnu hair"
    "gnu  hair"
    " gnu  hair"
    " gnu hair "
    "E. coli bacterium@\\bioname{E. coli} bacterium"
    "GNU Project"
    "gnu"
    "gnu!diet"
    "gnu!diet!wet season"
    "gnu!diet!dry season"
    "gnu!hair"
    "gnu!hair!color"
    "gnu!hair!DNA analysis"
    "gnu!hair!texture"
    "gnu!hair!thickness"
    "gnu!predators"
    "gnu!predators!crocodiles"
    "gnu!predators!hyenas"
    "gnu!predators!lions"
    "zythum (ancient Egyptian malt beverage)"
    "zoetrope"
    "zebu (cattle) (\\bioname{Bos taurus indicus})"
    "zebra"
    "yucca"
    "yak"
    "xylophone"
    "xylem (woody tissue of a plant)"
    "xenon (noble gas)"
    "X radiation"
    "X ray"
    "woodchuck (\\bioname{Marmota monax})"
    "wolverine"
    "wolf"
    "white-tailed deer (\\bioname{Odocoileus virginianus})"
    "whippet"
    "whale"
    "weasel"
    "water buffalo"
    "wart hog"
    "wapiti (\\bioname{Cervus canadensis})"
    "wanderoo"
    "walrus"
    "wallaby"
    "vulture"
    "vicuna (Vicugna vicugna)@vicu{\\~n}a (\\bioname{Vicugna vicugna})"
    "vampire bat"
    "unicorn"
    "turbot"
    "tuna"
    "toucan"
    "tiger (\\bioname{Panthera tigris})"
    "tapir"
    "tangun"
    "swordfish"
    "suslik"
    "sunfish"
    "skunk"
    "skink"
    "sapajou"
    "salamander"
    "saber-toothed cat"
    "Alces alces@\\bioname{Alces alces}"
    "Antilocapra americana@\\bioname{Antilocapra americana}"
    "Bos taurus indicus@\\bioname{Bos taurus indicus}"
    "Cervus canadensis@\\bioname{Cervus canadensis}"
    "Connochaetes gnou@\\bioname{Connochaetes gnou}"
    "Lama glama@\\bioname{Lama glama}"
    "Marmota monax@\\bioname{Marmota monax}"
    "Odocoileus virginianus@\\bioname{Odocoileus virginianus}"
    "Panthera tigris@\\bioname{Panthera tigris}"
    "Vicugna vicugna@\\bioname{Vicugna vicugna}"
    "Alces alces@\\bioname{Alces alces}|see{moose}"
    "Antilocapra americana@\\bioname{Antilocapra americana}|see{pronghorn}"
    "Cervus canadensis@\\bioname{Cervus canadensis}|see{elk}"
    "Cervus canadensis@\\bioname{Cervus canadensis}|see{wapiti}"
    "Connochaetes gnou@\\bioname{Connochaetes gnou}|see{gnu}"
    "Lama glama@\\bioname{Lama glama}|see{llama}"
    "Leopardus pardalis@\\bioname{Leopardus pardalis}|see{ocelot}"
    "Leopardus wiedii@\\bioname{Leopardus wiedii}|see{margay}"
    "Lynx canadensis@\\bioname{Lynx canadensis}|see{lynx}"
    "Lynx rufus@\\bioname{Lynx rufus}|see{bobcat}"
    "Marmota monax@\\bioname{Marmota monax}|see{woodchuck}"
    "Panthera onca@\\bioname{Panthera onca}|see{jaguar}"
    "Panthera tigris@\\bioname{Panthera tigris}|see{tiger}"
    "Puma concolor@\\bioname{Puma concolor}|see{cougar}"
    "Tragelaphus eurycerus@\\bioname{Tragelaphus eurycerus}|see{bongo}"
    "Trichechus inunguis@\\bioname{Trichechus inunguis}|see{manatee}"
    "Vicugna vicugna@\\bioname{Vicugna vicugna}|see{vicu{\\~n}a}"
    "African ungulate|see{gnu}"
    "ungulate|see{gnu}"
    "ungulate|see{impala}"
    "ungulate|see{kudu}"
    "ungulate|see{springbok}"
    "wildebeest|see{gnu}"
    "pachyderm|see{elephant}"
    "pachyderm|see{hippopotamus}"
    "pachyderm|see{rhinoceros}"
    "puma|see{cougar}"
    "rhino|see{rhinoceros}"
    "free software|seealso{GNU Project}"))
 :latex)

