(TeX-add-style-hook
 "chap4"
 (lambda ()
   (TeX-run-style-hooks
    "chapters/phrasal/phr-anchor-analysis"
    "chapters/phrasal/phr-CKY-based"
    "chapters/phrasal/phr-exp"
    "chapters/phrasal/phr-eval"
    "chapters/phrasal/phr-related-work"
    "chapters/phrasal/phr-conclusion")
   (LaTeX-add-index-entries
    "gnu"
    "gnu!predators"
    "gnu!predators!crocodiles"
    "gnu!predators!hyenas"
    "gnu!predators!lions"
    "gnu!nonpredators!aardvarks"
    "gnu!nonpredators!blesbok"
    "gnu!nonpredators!elephants"
    "gnu!nonpredators!gazelles"
    "gnu!nonpredators!giraffes"
    "gnu!nonpredators!zebras"
    "zythum (ancient Egyptian malt beverage)"
    "zoetrope"
    "zebu (cattle) (\\bioname{Bos taurus indicus})"
    "zebra"
    "yucca"
    "yak"
    "xylophone"
    "xylem (woody tissue of a plant)"
    "xenon (noble gas)"
    "X radiation"
    "X ray"
    "woodchuck (\\bioname{Marmota monax})"
    "wolverine"
    "wolf"
    "white-tailed deer (\\bioname{Odocoileus virginianus})"
    "whippet"
    "whale"
    "weasel"
    "water buffalo"
    "wart hog"
    "wapiti"
    "wanderoo"
    "walrus"
    "wallaby"
    "vulture"
    "vicuna (Vicugna vicugna)@vicu{\\~n}a (\\bioname{Vicugna vicugna})"
    "vampire bat"
    "unicorn"
    "turbot"
    "tuna"
    "toucan"
    "tiger (\\bioname{Panthera tigris})"
    "tapir"
    "tangun"
    "swordfish"
    "suslik"
    "sunfish"
    "skunk"
    "skink"
    "sapajou"
    "salamander"
    "saber-toothed cat"
    "rhinodon"
    "rhinodont"
    "rhinoceros"
    "rhinoceros horn"
    "rhinocerite"
    "rhinestone"
    "Rhineland"
    "Rhinegrave"
    "Rhine berry"
    "rhea"
    "rat"
    "raccoon"
    "Queensland viper"
    "quail"
    "quagga"
    "puffin"
    "pterodactyl"
    "pronghorn (\\bioname{Antilocapra americana})"
    "peccary"
    "panther"
    "panda"
    "opossum"
    "okapi"
    "octopus"
    "ocelot (\\bioname{Leopardus pardalis})"
    "nilgai"
    "Neanderthal"
    "nautilus"
    "narwhal"
    "muskrat"
    "musk ox"
    "moose (\\bioname{Alces alces})"
    "mastodon"
    "mastiff"
    "marmot (\\bioname{Marmota marmota})"
    "margay (\\bioname{Leopardus wiedii})"
    "manatee (\\bioname{Trichechus inunguis})"
    "mammoth"
    "lynx (\\bioname{Lynx canadensis})"
    "llama (\\bioname{Lama glama})"
    "lion"
    "leopard"
    "lemur"
    "lemming"
    "kudu"
    "kangaroo"
    "koala"
    "jerboa"
    "jaguar (\\bioname{Panthera onca})"
    "jackrabbit"
    "jackass"
    "jackal"
    "impala"
    "ibex"
    "hyena"
    "hippopotamus"
    "hartebeest"
    "giraffe"
    "gila monster"
    "gecko"
    "gazelle"
    "fox"
    "ferret"
    "elk (\\bioname{Cervus canadensis})"
    "elephant"
    "deer"
    "crocodile"
    "coyote"
    "cougar (\\bioname{Puma concolor})"
    "cheetah"
    "caribou"
    "bongo (\\bioname{Tragelaphus eurycerus})"
    "bobcat (\\bioname{Lynx rufus})"
    "bison"
    "beaver"
    "azymous (unleavened)"
    "aoudad"
    "antelope"
    "addax"
    "aardwolf"
    "aardvark"
    "Alces alces@\\bioname{Alces alces}"
    "Antilocapra americana@\\bioname{Antilocapra americana}"
    "Bos taurus indicus@\\bioname{Bos taurus indicus}"
    "Cervus canadensis@\\bioname{Cervus canadensis}"
    "Lama glama@\\bioname{Lama glama}"
    "Lynx canadensis@\\bioname{Lynx canadensis}"
    "Lynx rufus@\\bioname{Lynx rufus}"
    "Marmota monax@\\bioname{Marmota monax}"
    "Marmota marmota@\\bioname{Marmota marmota}"
    "Odocoileus virginianus@\\bioname{Odocoileus virginianus}"
    "Panthera onca@\\bioname{Panthera onca}"
    "Panthera tigris@\\bioname{Panthera tigris}"
    "Puma concolor@\\bioname{Puma concolor}"
    "Tragelaphus eurycerus@\\bioname{Tragelaphus eurycerus}"
    "Vicugna vicugna@\\bioname{Vicugna vicugna}"))
 :latex)

