(TeX-add-style-hook
 "chap5"
 (lambda ()
   (TeX-run-style-hooks
    "chapters/sentence/misc-motivation"
    "chapters/sentence/misc-task"
    "chapters/sentence/misc-devices"
    "chapters/sentence/misc-experiments"
    "chapters/sentence/misc-analysis"
    "chapters/sentence/misc-conclusion")
   (LaTeX-add-index-entries
    "gnu"
    "gnu!diet"
    "gnu!diet!wet season"
    "gnu!diet!dry season"
    "rhinodon"
    "rhinodont"
    "rhinoceros"
    "rhinoceros horn"
    "rhinocerite"
    "rhinestone"
    "Rhineland"
    "Rhinegrave"
    "Rhine berry"
    "rhea"
    "rat"
    "raccoon"
    "Queensland viper"
    "quail"
    "quagga"
    "puffin"
    "pterodactyl"
    "pronghorn (\\bioname{Antilocapra americana})"
    "peccary"
    "panther"
    "panda"
    "opossum"
    "okapi"
    "octopus"
    "ocelot (\\bioname{Leopardus pardalis})"
    "nilgai"
    "Neanderthal"
    "nautilus"
    "narwhal"
    "muskrat"
    "musk ox"
    "moose (\\bioname{Alces alces})"
    "mastodon"
    "mastiff"
    "marmot (\\bioname{Marmota marmota})"
    "margay (\\bioname{Leopardus wiedii})"
    "manatee (\\bioname{Trichechus inunguis})"
    "mammoth"
    "Alces alces@\\bioname{Alces alces}"
    "Antilocapra americana@\\bioname{Antilocapra americana}"
    "Marmota marmota@\\bioname{Marmota marmota}"))
 :latex)

